language: c

env:
  - CREATE_TOOLCHAIN=arm-none-eabi
  - CREATE_TOOLCHAIN=arm-unknown-linux-gnueabi
  - CREATE_TOOLCHAIN=cygwin-arm-unknown-linux-gnueabi CYGWIN_HOST=1

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service couchdb stop
  - sudo service dbus stop
  - sudo service udev stop  
  - sudo rm -rf /var/ramfs/mysql
  - sudo rm -rf /var/ramfs/postgresql
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - sudo apt-get update -qq

install:
  - sudo apt-get install gperf texinfo

before_script:
  - cd $TRAVIS_BUILD_DIR/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
  - export PATH="${PATH}:/tmp/ct-ng/bin"

script:
  - unset CC
  - unset LD_LIBRARY_PATH
  - cd $TRAVIS_BUILD_DIR
  - if [[ -n "${CYGWIN_HOST}" ]]; then sudo ./ubuntu-install-cygwin-gcc; fi
  - sudo apt-get install ash
  - mv ${CREATE_TOOLCHAIN}.config /tmp/.config
  - cd /tmp
  - ct-ng build.3

after_failure:
  - tail --lines=100 build.log
  - dmesg
