language: c

install:
  - sudo apt-get update
  - sudo apt-get install gperf

script:
  - cd $TRAVIS_BUILD_DIR/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
