language: c

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install gperf texinfo
  - sudo ln -sf ld.gold /usr/bin/ld

before_script:
  - cd $TRAVIS_BUILD_DIR/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
  - export PATH="${PATH}:/tmp/ct-ng/bin"

script:
  - unset CC
  - unset LD_LIBRARY_PATH
  - cd $TRAVIS_BUILD_DIR
  - mv arm-unknown-linux-gnueabi.config /tmp/.config
  - cd /tmp
  - ct-ng build.3

after_failure:
  - tail --lines=100 build.log
