#
# Copyright (C) 2014 Space Codesign Systems Inc.
# See COPYING file for licensing terms.
#

language: c

env:
  - CREATE_TOOLCHAIN=arm-none-eabi
  - CREATE_TOOLCHAIN=arm-unknown-linux-gnueabi
  - CREATE_TOOLCHAIN=arm_cyghost-unknown-linux-gnueabi CYGWIN_HOST=1
  - CREATE_TOOLCHAIN=x86_64-nptl-linux-gnu CYGWIN_HOST=1

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service couchdb stop
  - sudo service dbus stop
  - sudo service udev stop  
  - sudo rm -rf /var/ramfs/mysql
  - sudo rm -rf /var/ramfs/postgresql
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - sudo apt-get update -qq

install:
  - sudo apt-get install gperf texinfo

before_script:
  - cd ${TRAVIS_BUILD_DIR}/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
  - export PATH="${PATH}:/tmp/ct-ng/bin"

script:
  - unset CC
  - unset LD_LIBRARY_PATH
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ -n "${CYGWIN_HOST}" ]]; then sudo ./ubuntu-install-cygwin-gcc; fi
  - sudo apt-get install ash ccache expect s3cmd
  - echo "access_key = ${S3_BUILD_KEY_ID}" > ~/.s3cfg
  - echo "secret_key = ${S3_BUILD_KEY_SECRET}" >> ~/.s3cfg
  - export REMOTE_BASEDIR=s3://spacecodesign-dev/artifacts/oss/${TRAVIS_REPO_SLUG}
  - export REMOTE_CCACHE=${REMOTE_BASEDIR}/${CREATE_TOOLCHAIN}_ccache.tar.gz
  - export REMOTE_DEPLOYDIR=${REMOTE_BASEDIR}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_COMMIT}/${CREATE_TOOLCHAIN}
  - ./remote_ccache_get
  - mv ${CREATE_TOOLCHAIN}.config /tmp/.config
  - cd /tmp
  - CCACHE_SLOPPINESS=include_file_mtime CCACHE_COMPILERCHECK=mtime ${TRAVIS_BUILD_DIR}/ct-ng-driver.exp build.3

after_success:
  - ${TRAVIS_BUILD_DIR}/remote_ccache_put
  - ${TRAVIS_BUILD_DIR}/toolchain_deploy
  - export BUILD_STATUS=success

after_failure:
  - tail --lines=100 build.log
  - dmesg
  - export BUILD_STATUS=fail

after_script:
  - gzip build.log
  - s3cmd put --no-progress build.log.gz ${REMOTE_DEPLOYDIR}/build_${BUILD_STATUS}.log.gz

