#
# Copyright (C) 2014 Space Codesign Systems Inc.
# See COPYING file for licensing terms.
#

language: c

env:
  - CREATE_TOOLCHAIN=arm-none-eabi
  - CREATE_TOOLCHAIN=arm-unknown-linux-gnueabi
  - CREATE_TOOLCHAIN=cygwin-arm-unknown-linux-gnueabi CYGWIN_HOST=1

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service couchdb stop
  - sudo service dbus stop
  - sudo service udev stop  
  - sudo rm -rf /var/ramfs/mysql
  - sudo rm -rf /var/ramfs/postgresql
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - sudo apt-get update -qq

install:
  - sudo apt-get install gperf texinfo

before_script:
  - cd $TRAVIS_BUILD_DIR/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
  - export PATH="${PATH}:/tmp/ct-ng/bin"

script:
  - unset CC
  - unset LD_LIBRARY_PATH
  - cd $TRAVIS_BUILD_DIR
  - if [[ -n "${CYGWIN_HOST}" ]]; then sudo ./ubuntu-install-cygwin-gcc; fi
  - sudo apt-get install ash ccache s3cmd
  - echo "access_key = ${S3_BUILD_KEY_ID}" > ~/.s3cfg
  - echo "secret_key = ${S3_BUILD_KEY_SECRET}" >> ~/.s3cfg
  - export REMOTE_CCACHE=s3://spacecodesign-dev/build/${CREATE_TOOLCHAIN}/ccache.tar.gz
  - if [[ -n "$(s3cmd ls ${REMOTE_CCACHE} | grep ${REMOTE_CCACHE}$)" ]] ; then s3cmd get --no-progress ${REMOTE_CCACHE} ccache.tar.gz ; tar -zxf ccache.tar.gz -C ~ ; fi
  - mv ${CREATE_TOOLCHAIN}.config /tmp/.config
  - cd /tmp
  - CCACHE_SLOPPINESS=include_file_mtime CCACHE_COMPILERCHECK=mtime ct-ng build.3

after_success:
  - tar -zcf ccache.tar.gz -C ~ .ccache
  - s3cmd put --no-progress ccache.tar.gz ${REMOTE_CCACHE}

after_failure:
  - tail --lines=100 build.log
  - dmesg
  - gzip build.log
  - s3cmd put --no-progress build.log.gz s3://spacecodesign-dev/build/${CREATE_TOOLCHAIN}/build_fail.log.gz

