language: c

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service couchdb stop
  - sudo rm -rf /var/ramfs/mysql
  - sudo rm -rf /var/ramfs/postgresql
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - sudo apt-get update

install:
  - sudo apt-get install gperf texinfo

before_script:
  - cd $TRAVIS_BUILD_DIR/crosstool-ng
  - ./bootstrap
  - ./configure --prefix=/tmp/ct-ng
  - make
  - make install
  - export PATH="${PATH}:/tmp/ct-ng/bin"

script:
  - unset CC
  - unset LD_LIBRARY_PATH
  - cd $TRAVIS_BUILD_DIR
  - sudo ./ubuntu-install-cygwin-gcc
  - sudo apt-get install ash
  - mv cygwin-arm-unknown-linux-gnueabi.config /tmp/.config
  - cd /tmp
  - ct-ng build.4

after_failure:
  - tail --lines=100 build.log
  - dmesg
