#!/bin/sh
set -ex

if [ -z "${REMOTE_CCACHE}" ] ; then
  echo "Error: REMOTE_CCACHE not set"; exit 1
fi

if [ -n "$(s3cmd ls ${REMOTE_CCACHE} | grep ${REMOTE_CCACHE}$)" ] ; then
  ccache_tgz=$(mktemp)
  s3cmd --force --no-progress get ${REMOTE_CCACHE} ${ccache_tgz}
  tar -zxf ${ccache_tgz} -C ~
  rm ${ccache_tgz}
fi
