#!/bin/sh
set -ex

if [ -z "${CREATE_TOOLCHAIN}" ] ; then
  echo "Error: CREATE_TOOLCHAIN not set"; exit 1
fi

if [ -z "${REMOTE_DEPLOYDIR}" ] ; then
  echo "Error: REMOTE_DEPLOYDIR not set"; exit 1
fi

toolchain_zip=$(mktemp)
pushd /tmp/toolchains
zip -qr ${toolchain_zip} ${CREATE_TOOLCHAIN}
s3cmd --no-progress put ${toolchain_zip} ${REMOTE_DEPLOYDIR}/${CREATE_TOOLCHAIN}.zip
rm ${toolchain_zip}

