#!/bin/sh
set -ex

if ! command -v rpm >/dev/null 2>&1 ; then
  apt-get install rpm
fi

RPM="rpm --quiet --install --nodeps --replacepkgs"
REPO="ftp://ftp.cygwinports.org/pub/cygwinports"
$RPM $REPO/EL6/RPMS/x86_64/cygwin32-binutils-2.24.51-1.el6.x86_64.rpm
$RPM $REPO/EL6/RPMS/x86_64/cygwin32-cpp-4.8.2-2.el6.x86_64.rpm
$RPM $REPO/EL6/RPMS/x86_64/cygwin32-gcc-4.8.2-2.el6.x86_64.rpm
$RPM $REPO/EL6/RPMS/x86_64/cygwin32-gcc-c++-4.8.2-2.el6.x86_64.rpm
$RPM $REPO/fedora-cygwin/RPMS/noarch/cygwin32-1.7.31-1.noarch.rpm
$RPM $REPO/fedora-cygwin/RPMS/noarch/cygwin32-w32api-headers-3.1.0-2.noarch.rpm
$RPM $REPO/fedora-cygwin/RPMS/noarch/cygwin32-w32api-runtime-3.1.0-1.noarch.rpm
$RPM $REPO/fedora-cygwin/RPMS/noarch/cygwin32-ncurses-5.9-2.20140524.noarch.rpm
$RPM $REPO/fedora-cygwin/RPMS/noarch/cygwin32-expat-2.1.0-2.noarch.rpm

ln -sf /usr/lib/x86_64-linux-gnu/libmpfr.so.4 /usr/lib/x86_64-linux-gnu/libmpfr.so.1
ln -sf /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/x86_64-linux-gnu/libgmp.so.3
